name: Deploy Blazor App using GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish PortfolioXI/PortfolioXI.csproj -c Release -o release

      - name: Deploy using JamesIves Action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
          clean: true

