name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - main  # 替换为你的默认分支名（如 master）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # 根据你使用的 .NET 版本调整

      - name: Publish Blazor WebAssembly
        run: dotnet publish PortfolioXI/PortfolioXI.csproj -c Release -o release \
             /p:PublishTrimmed=false /p:PublishSingleFile=false

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
