name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Blazor WebAssembly app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET project
        run: dotnet publish PortfolioXI/PortfolioXI.csproj -c Release -o release

      - name: Move output
        run: |
          mkdir output
          cp -r release/wwwroot/* output

      - name: Add .nojekyll
        run: touch output/.nojekyll

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # 这必须是你 Blazor 项目发布后的 index.html 所在目录
          publish_dir: ./PortfolioXI/bin/Release/net8.0/publish/wwwroot
